name: Deploy Splunk App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: [ self-hosted, splunk ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build artifact
        run: tar -czf soc_lab_app.tgz soc_lab_app

      - name: Pack app
        run: tar -czf /tmp/soc_lab_app.tgz soc_lab_app

      - name: Deploy locally
        env:
          SPLUNK_HOME: ${{ secrets.REMOTE_SPLUNK_HOME }}
          APP_NAME: ${{ secrets.REMOTE_APP_NAME || 'soc_lab' }}
        run: |
          set -e
          sudo mkdir -p "$SPLUNK_HOME/etc/apps/$APP_NAME"
          sudo tar -xzf /tmp/soc_lab_app.tgz -C "$SPLUNK_HOME/etc/apps/$APP_NAME" --strip-components=1

      - name: Restart Splunk
        env:
          SPLUNK_HOME: ${{ secrets.REMOTE_SPLUNK_HOME }}
          SPLUNK_USERNAME: ${{ secrets.SPLUNK_USERNAME }}
          SPLUNK_PASSWORD: ${{ secrets.SPLUNK_PASSWORD }}
        run: |
          "$SPLUNK_HOME/bin/splunk" restart -auth "$SPLUNK_USERNAME:$SPLUNK_PASSWORD"
          "$SPLUNK_HOME/bin/splunk" status
