name: Deploy Splunk App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: [ self-hosted, splunk ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build artifact
        run: tar -czf soc_lab_app.tgz soc_lab_app

      - name: Pack app for local deployment
        run: tar -czf /tmp/soc_lab_app.tgz soc_lab_app

      - name: Deploy locally
        env:
          SPLUNK_HOME: ${{ secrets.REMOTE_SPLUNK_HOME }}
          APP_NAME: ${{ secrets.REMOTE_APP_NAME || 'soc_lab' }}
        run: |
          set -e
          sudo mkdir -p "$SPLUNK_HOME/etc/apps/$APP_NAME"
          sudo tar -xzf /tmp/soc_lab_app.tgz -C "$SPLUNK_HOME/etc/apps/$APP_NAME" --strip-components=1
          sudo find "$SPLUNK_HOME/etc/apps/$APP_NAME" -type f -maxdepth 2 -print | head -n 20

      - name: Restart via systemctl with clean env
        run: |
          set -e
          /opt/splunk/bin/splunk version
          sudo env -i PATH=/usr/sbin:/usr/bin:/bin /bin/systemctl restart splunk || sudo env -i PATH=/usr/sbin:/usr/bin:/bin /bin/systemctl restart Splunkd
          sudo env -i PATH=/usr/sbin:/usr/bin:/bin /bin/systemctl status splunk || sudo env -i PATH=/usr/sbin:/usr/bin:/bin /bin/systemctl status Splunkd
