name: Deploy Splunk App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: [ self-hosted, splunk ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build artifact
        run: tar -czf soc_lab_app.tgz soc_lab_app

      - name: Copy artifact to remote
        uses: appleboy/scp-action@v1        
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || '22' }}
          source: "soc_lab_app.tgz,scripts/remote_install.sh"
          target: "/tmp"
      - name: Verify copy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || '22' }}
          script: |
            ls -l /tmp/remote_install.sh || exit 1
            ls -lh /tmp/soc_lab_app.tgz || exit 1
          
      - name: Run remote preflight + deploy + restart + healthcheck
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || '22' }}
          script_stop: true
          envs: REMOTE_SPLUNK_HOME,REMOTE_APP_NAME,USE_SYSTEMCTL,HEALTH_TIMEOUT,SPLUNK_USERNAME,SPLUNK_PASSWORD
          script: |
            chmod +x /tmp/remote_install.sh
            /tmp/remote_install.sh
        env:
          REMOTE_SPLUNK_HOME: ${{ secrets.REMOTE_SPLUNK_HOME }}
          REMOTE_APP_NAME: ${{ secrets.REMOTE_APP_NAME || 'soc_lab' }}
          USE_SYSTEMCTL: ${{ secrets.USE_SYSTEMCTL || '1' }}
          HEALTH_TIMEOUT: ${{ secrets.HEALTH_TIMEOUT || '120' }}
          SPLUNK_USERNAME: ${{ secrets.SPLUNK_USERNAME }}
          SPLUNK_PASSWORD: ${{ secrets.SPLUNK_PASSWORD }}

