name: Deploy Splunk App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: [ self-hosted, splunk ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build artifact
        run: tar -czf soc_lab_app.tgz soc_lab_app

      - name: Pack app for local deployment
        run: tar -czf /tmp/soc_lab_app.tgz soc_lab_app

      - name: Deploy locally
        env:
          SPLUNK_HOME: ${{ secrets.REMOTE_SPLUNK_HOME }}
          APP_NAME: ${{ secrets.REMOTE_APP_NAME || 'soc_lab' }}
        run: |
          set -e
          sudo mkdir -p "$SPLUNK_HOME/etc/apps/$APP_NAME"
          sudo tar -xzf /tmp/soc_lab_app.tgz -C "$SPLUNK_HOME/etc/apps/$APP_NAME" --strip-components=1
          sudo find "$SPLUNK_HOME/etc/apps/$APP_NAME" -type f -maxdepth 2 -print | head -n 20

      - name: Restart via systemctl with clean env
        run: |
          set -e
          echo "→ Restart Splunk service (clean environment)"
          /opt/splunk/bin/splunk version
          sudo env -i PATH=/usr/sbin:/usr/bin:/bin /bin/systemctl restart splunk || sudo env -i PATH=/usr/sbin:/usr/bin:/bin /bin/systemctl restart Splunkd
          sudo env -i PATH=/usr/sbin:/usr/bin:/bin /bin/systemctl status splunk || sudo env -i PATH=/usr/sbin:/usr/bin:/bin /bin/systemctl status Splunkd
          echo "→ Run btool check for syntax issues"
          sudo -E -u splunk "$SPLUNK_HOME/bin/splunk" btool check --debug || true
          echo "→ Health check on management API (8089)"
          for i in {1..30}; do
            if curl -sk -u "$SPLUNK_USERNAME:$SPLUNK_PASSWORD" https://127.0.0.1:8089/services/server/info >/dev/null; then
              echo "Splunkd API OK ✅"
              exit 0
            fi
            echo "Waiting for Splunkd (try $i/30)..."
            sleep 5
          done
          echo "❌ ERROR: Splunkd API not responding after 150s"
          exit 1