name: Deploy Splunk App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build artifact
        run: |
          tar -czf soc_lab_app.tgz soc_lab_app

      - name: Copy artifact to remote
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          source: "soc_lab_app.tgz, scripts/remote_install.sh"
          target: "/tmp"

      - name: Run remote preflight + deploy + restart + healthcheck
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script_stop: true
          envs: REMOTE_SPLUNK_HOME,REMOTE_APP_NAME,USE_SYSTEMCTL,HEALTH_TIMEOUT,SPLUNK_USERNAME,SPLUNK_PASSWORD
          script: |
            chmod +x /tmp/remote_install.sh
            export REMOTE_SPLUNK_HOME="${{ secrets.REMOTE_SPLUNK_HOME }}"
            export REMOTE_APP_NAME="${{ secrets.REMOTE_APP_NAME || 'soc_lab' }}"
            export USE_SYSTEMCTL="${{ secrets.USE_SYSTEMCTL || '1' }}"
            export HEALTH_TIMEOUT="${{ secrets.HEALTH_TIMEOUT || '120' }}"
            export SPLUNK_USERNAME="${{ secrets.SPLUNK_USERNAME || '' }}"
            export SPLUNK_PASSWORD="${{ secrets.SPLUNK_PASSWORD || '' }}"
            /tmp/remote_install.sh
